general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para iniciar o bloqueio
    before_sleep_cmd = loginctl lock-session    # Bloqueia antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Liga a tela ao acordar
}

listener {
    timeout = 600                                 # 10 minutos
    on-timeout = loginctl lock-session            # Bloqueia a tela
}

listener {
    timeout = 480                                 # 8 minutos
    on-timeout = hyprctl dispatch dpms off        # Desliga o monitor
    on-resume = hyprctl dispatch dpms on          # Liga o monitor ao mexer o mouse
}
